# Generated by Django 5.2.17 on 2026-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('clothes', 'Clothes'), ('electronics', 'Electronics'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
